# Generated by Django 5.0.1 on 2024-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_expense_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('AFR', 'Africa'), ('ASIME', 'Asia and Middle East'), ('EUR', 'Europe'), ('OCE', 'Oceania'), ('NAC', 'North and Central America & Caribbean'), ('SOA', 'South America')], default='AFR', max_length=5),
        ),
    ]
