# Generated by Django 5.0.1 on 2024-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_destination_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['region', 'name']},
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
    ]
