# Generated by Django 5.0.1 on 2024-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('landmark', 'Landmark'), ('island', 'Island'), ('country', 'Country')], default='city', max_length=50),
        ),
    ]
