# Generated by Django 5.0.1 on 2024-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_destination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_attribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
