# Generated by Django 5.0.1 on 2024-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_destination_image_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('landmark', 'Landmark'), ('island', 'Island'), ('province', 'Province'), ('country', 'Country')], default='city', max_length=50),
        ),
    ]
