# Generated by Django 5.0.1 on 2024-11-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_attraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='longitude',
        ),
    ]
