# Generated by Django 5.0.1 on 2024-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_remove_activity_latitude_remove_activity_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
