# Generated by Django 5.0.1 on 2024-11-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='travel.destination'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'destination')},
        ),
    ]
